#Use official debian jessie docker image
FROM debian:stretch
LABEL pace=true
WORKDIR /
RUN apt-get update && apt-get install -y build-essential vim procps
ADD qtorch /qtorch
RUN cd qtorch/nlopt-2.4.2 &&\
    ./configure &&\
    make &&\
    make install &&\
    cd .. &&\
    make td &&\
    make cut
ADD run.sh /run.sh

RUN ["chmod", "+x", "run.sh"]






