#Use official debian jessie docker image
FROM debian:stretch
LABEL pace=true
WORKDIR /
RUN apt-get update && apt-get -y install make procps autotools-dev automake g++ git libboost-all-dev libtool && \
git clone https://github.com/freetdi/p17 && \
git clone https://github.com/bingmann/stx-btree && \
cd /stx-btree/ && \
./configure && \
make && \
make install && \
cd .. && \
make -C /p17/
ADD run.sh /run.sh
RUN ["chmod", "+xw", "run.sh"]
