#Use official Alpine 3.6 docker image

FROM python:stretch
LABEL pace=true
WORKDIR /
RUN apt-get update && apt-get install bash
ADD run.sh /run.sh
ADD quickbb_64 /quickbb_64
ADD graph-to-cnf.py /graph-to-cnf.py
ADD peo-to-td.py /peo-to-td.py
RUN ["chmod", "+x", "run.sh"]
RUN ["chmod", "+x", "quickbb_64" ]
ENTRYPOINT [ "/bin/bash" ]
