#Use official Alpine 3.6 docker image

FROM python:stretch
LABEL pace=true
WORKDIR /
RUN apt-get update && apt-get install bash
ADD run.sh /run.sh
ADD graph-to-cnf.py /graph-to-cnf.py
ADD peo-to-td.py /peo-to-td.py
RUN wget http://www.hlt.utdallas.edu/~vgogate/quickbb_64 &&\
    chmod +x run.sh &&\
    chmod +x quickbb_64
