#Use official debian slim docker image
FROM openjdk:10-jre-slim
LABEL pace=true
WORKDIR /
ADD meiji /meiji/
ADD run.sh /run.sh
RUN apt-get update && apt-get install -y make openjdk-10-jdk && \
    javac -d /classes/ /meiji/tw/exact/*.java && \
    chmod +x run.sh && \
    chmod +x /meiji/tw-exact







