#Use official debian slim docker image
FROM openjdk:10-jre-slim
LABEL pace=true
WORKDIR /
COPY meiji /meiji/
RUN apt-get update && apt-get install -y make openjdk-10-jdk && \
    javac -d /classes/ /meiji/tw/heuristic/*.java
COPY run.sh /run.sh
RUN chmod +x /run.sh





